---
- all:
    children:
      app_server:
        - app1.example.com              #Hostname/IP of the app server
        - app2.example.com
      db_server:
        - db1.example.com               #Hostname/IP of the deb server
